[package]
authors = ["Xu Qihang <akucxy@163.com>"]
description = "Containers implemented by B+ trees, similar to Rust's `BTreeMap` and `BTreeSet`."
edition = "2021"
name = "bptree"
version = "0.1.0"

[dev-dependencies]
rand = "0.8"
